/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<
      'root',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '$error': RouteRecordInfo<
      '$error',
      '/:error(.*)',
      { error: ParamValue<true> },
      { error: ParamValue<false> },
      | never
    >,
    'account-all': RouteRecordInfo<
      'account-all',
      '/account-all',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'account-settings': RouteRecordInfo<
      'account-settings',
      '/account-settings',
      Record<never, never>,
      Record<never, never>,
      | 'account-settings-account-tab'
      | 'account-settings-customize-tab'
      | 'account-settings-invoices-tab'
      | 'account-settings-plans-tab'
      | 'account-settings-security-tab'
    >,
    'account-settings-account-tab': RouteRecordInfo<
      'account-settings-account-tab',
      '/account-settings/account-tab',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'account-settings-customize-tab': RouteRecordInfo<
      'account-settings-customize-tab',
      '/account-settings/customize-tab',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'account-settings-invoices-tab': RouteRecordInfo<
      'account-settings-invoices-tab',
      '/account-settings/invoices-tab',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'account-settings-plans-tab': RouteRecordInfo<
      'account-settings-plans-tab',
      '/account-settings/plans-tab',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'account-settings-security-tab': RouteRecordInfo<
      'account-settings-security-tab',
      '/account-settings/security-tab',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ai-agent': RouteRecordInfo<
      'ai-agent',
      '/ai-agent',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'channels': RouteRecordInfo<
      'channels',
      '/channels',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'chat': RouteRecordInfo<
      'chat',
      '/chat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'chatbot': RouteRecordInfo<
      'chatbot',
      '/chatbot',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'chatbot-flow': RouteRecordInfo<
      'chatbot-flow',
      '/chatbot-flow',
      Record<never, never>,
      Record<never, never>,
      | 'chatbot-flow-id'
    >,
    'chatbot-flow-id': RouteRecordInfo<
      'chatbot-flow-id',
      '/chatbot-flow/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'config': RouteRecordInfo<
      'config',
      '/config',
      Record<never, never>,
      Record<never, never>,
      | 'config-channels-tab'
      | 'config-creditcard-tab'
      | 'config-method-payments-tab'
      | 'config-nfse-tab'
      | 'config-notifications-tab'
    >,
    'config-channels-tab': RouteRecordInfo<
      'config-channels-tab',
      '/config/channels-tab',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'config-creditcard-tab': RouteRecordInfo<
      'config-creditcard-tab',
      '/config/creditcard-tab',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'config-method-payments-tab': RouteRecordInfo<
      'config-method-payments-tab',
      '/config/method-payments-tab',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'config-nfse-tab': RouteRecordInfo<
      'config-nfse-tab',
      '/config/nfse-tab',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'config-notifications-tab': RouteRecordInfo<
      'config-notifications-tab',
      '/config/notifications-tab',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'contact': RouteRecordInfo<
      'contact',
      '/contact',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'contact-and-groups': RouteRecordInfo<
      'contact-and-groups',
      '/contact-and-groups',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'contact-group': RouteRecordInfo<
      'contact-group',
      '/contact-group',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'cross-sell': RouteRecordInfo<
      'cross-sell',
      '/cross-sell',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'expenditure': RouteRecordInfo<
      'expenditure',
      '/expenditure',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'forgot-password': RouteRecordInfo<
      'forgot-password',
      '/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'integration': RouteRecordInfo<
      'integration',
      '/integration',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'label': RouteRecordInfo<
      'label',
      '/label',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'login': RouteRecordInfo<
      'login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'message': RouteRecordInfo<
      'message',
      '/message',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'not-authorized': RouteRecordInfo<
      'not-authorized',
      '/not-authorized',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'plan': RouteRecordInfo<
      'plan',
      '/plan',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'plan-expired': RouteRecordInfo<
      'plan-expired',
      '/plan-expired',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'plans': RouteRecordInfo<
      'plans',
      '/plans',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'plans-checkout': RouteRecordInfo<
      'plans-checkout',
      '/plans-checkout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'register': RouteRecordInfo<
      'register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'release': RouteRecordInfo<
      'release',
      '/release',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reports-attendances': RouteRecordInfo<
      'reports-attendances',
      '/reports-attendances',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reports-clients': RouteRecordInfo<
      'reports-clients',
      '/reports-clients',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reports-conversation-history': RouteRecordInfo<
      'reports-conversation-history',
      '/reports-conversation-history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reports-financial': RouteRecordInfo<
      'reports-financial',
      '/reports-financial',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reports-sales': RouteRecordInfo<
      'reports-sales',
      '/reports-sales',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reports-satisfaction': RouteRecordInfo<
      'reports-satisfaction',
      '/reports-satisfaction',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reports-users': RouteRecordInfo<
      'reports-users',
      '/reports-users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'role': RouteRecordInfo<
      'role',
      '/role',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'schedule': RouteRecordInfo<
      'schedule',
      '/schedule',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'sector': RouteRecordInfo<
      'sector',
      '/sector',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'server': RouteRecordInfo<
      'server',
      '/server',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'user': RouteRecordInfo<
      'user',
      '/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | 'root'
      views:
        | never
    }
    'src/pages/[...error].vue': {
      routes:
        | '$error'
      views:
        | never
    }
    'src/pages/account-all.vue': {
      routes:
        | 'account-all'
      views:
        | never
    }
    'src/pages/account-settings.vue': {
      routes:
        | 'account-settings'
        | 'account-settings-account-tab'
        | 'account-settings-customize-tab'
        | 'account-settings-invoices-tab'
        | 'account-settings-plans-tab'
        | 'account-settings-security-tab'
      views:
        | 'default'
    }
    'src/pages/account-settings/account-tab.vue': {
      routes:
        | 'account-settings-account-tab'
      views:
        | never
    }
    'src/pages/account-settings/customize-tab.vue': {
      routes:
        | 'account-settings-customize-tab'
      views:
        | never
    }
    'src/pages/account-settings/invoices-tab.vue': {
      routes:
        | 'account-settings-invoices-tab'
      views:
        | never
    }
    'src/pages/account-settings/plans-tab.vue': {
      routes:
        | 'account-settings-plans-tab'
      views:
        | never
    }
    'src/pages/account-settings/security-tab.vue': {
      routes:
        | 'account-settings-security-tab'
      views:
        | never
    }
    'src/pages/ai-agent.vue': {
      routes:
        | 'ai-agent'
      views:
        | never
    }
    'src/pages/channels.vue': {
      routes:
        | 'channels'
      views:
        | never
    }
    'src/pages/chat.vue': {
      routes:
        | 'chat'
      views:
        | never
    }
    'src/pages/chatbot.vue': {
      routes:
        | 'chatbot'
      views:
        | never
    }
    'src/pages/chatbot-flow.vue': {
      routes:
        | 'chatbot-flow'
        | 'chatbot-flow-id'
      views:
        | 'default'
    }
    'src/pages/chatbot-flow/[id].vue': {
      routes:
        | 'chatbot-flow-id'
      views:
        | never
    }
    'src/pages/config.vue': {
      routes:
        | 'config'
        | 'config-channels-tab'
        | 'config-creditcard-tab'
        | 'config-method-payments-tab'
        | 'config-nfse-tab'
        | 'config-notifications-tab'
      views:
        | 'default'
    }
    'src/pages/config/channels-tab.vue': {
      routes:
        | 'config-channels-tab'
      views:
        | never
    }
    'src/pages/config/creditcard-tab.vue': {
      routes:
        | 'config-creditcard-tab'
      views:
        | never
    }
    'src/pages/config/method-payments-tab.vue': {
      routes:
        | 'config-method-payments-tab'
      views:
        | never
    }
    'src/pages/config/nfse-tab.vue': {
      routes:
        | 'config-nfse-tab'
      views:
        | never
    }
    'src/pages/config/notifications-tab.vue': {
      routes:
        | 'config-notifications-tab'
      views:
        | never
    }
    'src/pages/contact.vue': {
      routes:
        | 'contact'
      views:
        | never
    }
    'src/pages/contact-and-groups.vue': {
      routes:
        | 'contact-and-groups'
      views:
        | never
    }
    'src/pages/contact-group.vue': {
      routes:
        | 'contact-group'
      views:
        | never
    }
    'src/pages/cross-sell.vue': {
      routes:
        | 'cross-sell'
      views:
        | never
    }
    'src/pages/expenditure.vue': {
      routes:
        | 'expenditure'
      views:
        | never
    }
    'src/pages/forgot-password.vue': {
      routes:
        | 'forgot-password'
      views:
        | never
    }
    'src/pages/integration.vue': {
      routes:
        | 'integration'
      views:
        | never
    }
    'src/pages/label.vue': {
      routes:
        | 'label'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | 'login'
      views:
        | never
    }
    'src/pages/message.vue': {
      routes:
        | 'message'
      views:
        | never
    }
    'src/pages/not-authorized.vue': {
      routes:
        | 'not-authorized'
      views:
        | never
    }
    'src/pages/plan.vue': {
      routes:
        | 'plan'
      views:
        | never
    }
    'src/pages/plan-expired.vue': {
      routes:
        | 'plan-expired'
      views:
        | never
    }
    'src/pages/plans.vue': {
      routes:
        | 'plans'
      views:
        | never
    }
    'src/pages/plans-checkout.vue': {
      routes:
        | 'plans-checkout'
      views:
        | never
    }
    'src/pages/register.vue': {
      routes:
        | 'register'
      views:
        | never
    }
    'src/pages/release.vue': {
      routes:
        | 'release'
      views:
        | never
    }
    'src/pages/reports-attendances.vue': {
      routes:
        | 'reports-attendances'
      views:
        | never
    }
    'src/pages/reports-clients.vue': {
      routes:
        | 'reports-clients'
      views:
        | never
    }
    'src/pages/reports-conversation-history.vue': {
      routes:
        | 'reports-conversation-history'
      views:
        | never
    }
    'src/pages/reports-financial.vue': {
      routes:
        | 'reports-financial'
      views:
        | never
    }
    'src/pages/reports-sales.vue': {
      routes:
        | 'reports-sales'
      views:
        | never
    }
    'src/pages/reports-satisfaction.vue': {
      routes:
        | 'reports-satisfaction'
      views:
        | never
    }
    'src/pages/reports-users.vue': {
      routes:
        | 'reports-users'
      views:
        | never
    }
    'src/pages/role.vue': {
      routes:
        | 'role'
      views:
        | never
    }
    'src/pages/schedule.vue': {
      routes:
        | 'schedule'
      views:
        | never
    }
    'src/pages/sector.vue': {
      routes:
        | 'sector'
      views:
        | never
    }
    'src/pages/server.vue': {
      routes:
        | 'server'
      views:
        | never
    }
    'src/pages/user.vue': {
      routes:
        | 'user'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
