/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<
      'root',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '$error': RouteRecordInfo<
      '$error',
      '/:error(.*)',
      { error: ParamValue<true> },
      { error: ParamValue<false> },
      | never
    >,
    'account': RouteRecordInfo<
      'account',
      '/account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'channels': RouteRecordInfo<
      'channels',
      '/channels',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'chat': RouteRecordInfo<
      'chat',
      '/chat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'contact': RouteRecordInfo<
      'contact',
      '/contact',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'contact-and-groups': RouteRecordInfo<
      'contact-and-groups',
      '/contact-and-groups',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'contact-group': RouteRecordInfo<
      'contact-group',
      '/contact-group',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'cross-sell': RouteRecordInfo<
      'cross-sell',
      '/cross-sell',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'expenditure': RouteRecordInfo<
      'expenditure',
      '/expenditure',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'label': RouteRecordInfo<
      'label',
      '/label',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'login': RouteRecordInfo<
      'login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'message': RouteRecordInfo<
      'message',
      '/message',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'not-authorized': RouteRecordInfo<
      'not-authorized',
      '/not-authorized',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'plan': RouteRecordInfo<
      'plan',
      '/plan',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reports-clients': RouteRecordInfo<
      'reports-clients',
      '/reports-clients',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reports-financial': RouteRecordInfo<
      'reports-financial',
      '/reports-financial',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reports-sales': RouteRecordInfo<
      'reports-sales',
      '/reports-sales',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reports-users': RouteRecordInfo<
      'reports-users',
      '/reports-users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'role': RouteRecordInfo<
      'role',
      '/role',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'sector': RouteRecordInfo<
      'sector',
      '/sector',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'server': RouteRecordInfo<
      'server',
      '/server',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'user': RouteRecordInfo<
      'user',
      '/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | 'root'
      views:
        | never
    }
    'src/pages/[...error].vue': {
      routes:
        | '$error'
      views:
        | never
    }
    'src/pages/account.vue': {
      routes:
        | 'account'
      views:
        | never
    }
    'src/pages/channels.vue': {
      routes:
        | 'channels'
      views:
        | never
    }
    'src/pages/chat.vue': {
      routes:
        | 'chat'
      views:
        | never
    }
    'src/pages/contact.vue': {
      routes:
        | 'contact'
      views:
        | never
    }
    'src/pages/contact-and-groups.vue': {
      routes:
        | 'contact-and-groups'
      views:
        | never
    }
    'src/pages/contact-group.vue': {
      routes:
        | 'contact-group'
      views:
        | never
    }
    'src/pages/cross-sell.vue': {
      routes:
        | 'cross-sell'
      views:
        | never
    }
    'src/pages/expenditure.vue': {
      routes:
        | 'expenditure'
      views:
        | never
    }
    'src/pages/label.vue': {
      routes:
        | 'label'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | 'login'
      views:
        | never
    }
    'src/pages/message.vue': {
      routes:
        | 'message'
      views:
        | never
    }
    'src/pages/not-authorized.vue': {
      routes:
        | 'not-authorized'
      views:
        | never
    }
    'src/pages/plan.vue': {
      routes:
        | 'plan'
      views:
        | never
    }
    'src/pages/reports-clients.vue': {
      routes:
        | 'reports-clients'
      views:
        | never
    }
    'src/pages/reports-financial.vue': {
      routes:
        | 'reports-financial'
      views:
        | never
    }
    'src/pages/reports-sales.vue': {
      routes:
        | 'reports-sales'
      views:
        | never
    }
    'src/pages/reports-users.vue': {
      routes:
        | 'reports-users'
      views:
        | never
    }
    'src/pages/role.vue': {
      routes:
        | 'role'
      views:
        | never
    }
    'src/pages/sector.vue': {
      routes:
        | 'sector'
      views:
        | never
    }
    'src/pages/server.vue': {
      routes:
        | 'server'
      views:
        | never
    }
    'src/pages/user.vue': {
      routes:
        | 'user'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
