import { injectable } from 'tsyringe';
import { createWorker } from './methods/createWorker';
import { listWorker } from './methods/listWorker';
import { listWorkerServers } from './methods/listWorkerServers';
import { updateWorker } from './methods/updateWorker';
import { viewWorker } from './methods/viewWorker';
import { deleteWorker } from './methods/deleteWorker';
import { changeStatusConnection } from './methods/changeStatusConnection';
import { workerConnectionLogs } from './methods/workerConnectionLogs';
import { recreateWorker } from './methods/recreateWorker';
import { resetWorkerConnection } from './methods/resetWorkerConnection';
import { uploadProfileStatus } from './methods/uploadProfileStatus';
import { listProfileStatus } from './methods/listProfileStatus';
import { updateProfileStatus } from './methods/updateProfileStatus';
import { deleteProfileStatus } from './methods/deleteProfileStatus';
import { uploadProfileInfo } from './methods/uploadProfileInfo';
import { viewProfileInfo } from './methods/viewProfileInfo';
import { viewWorkerConfig } from './methods/viewWorkerConfig';
import { updateWorkerConfig } from './methods/updateWorkerConfig';
import { updateTransferProtocolText } from './methods/updateTransferProtocolText';
import { viewTransferProtocolText } from './methods/viewTransferProtocolText';
import { updateTransferProtocolSectorText } from './methods/updateTransferProtocolSectorText';
import { viewTransferProtocolSectorText } from './methods/viewTransferProtocolSectorText';
import { updateTransferProtocolSectorAndUserText } from './methods/updateTransferProtocolSectorAndUserText';
import { viewTransferProtocolSectorAndUserText } from './methods/viewTransferProtocolSectorAndUserText';
import { updateStartProtocolText } from './methods/updateStartProtocolText';
import { viewStartProtocolText } from './methods/viewStartProtocolText';
import { updateSimultaneousAttendance } from './methods/updateSimultaneousAttendance';
import { viewSimultaneousAttendance } from './methods/viewSimultaneousAttendance';
import { updateTypingSimulation } from './methods/updateTypingSimulation';
import { viewTypingSimulation } from './methods/viewTypingSimulation';
import { updateShowMessageOnCall } from './methods/updateShowMessageOnCall';
import { viewShowMessageOnCall } from './methods/viewShowMessageOnCall';
import { updateSendMessageOnFinishAttendance } from './methods/updateSendMessageOnFinishAttendance';
import { viewSendMessageOnFinishAttendance } from './methods/viewSendMessageOnFinishAttendance';
import { updateChatbot } from './methods/updateChatbot';
import { viewChatbot } from './methods/viewChatbot';
import { viewAiAgentConfig } from './methods/viewAiAgentConfig';
import { updateAiAgentConfig } from './methods/updateAiAgentConfig';
import { viewAttendanceHours } from './methods/viewAttendanceHours';
import { updateAttendanceHours } from './methods/updateAttendanceHours';
import { viewAttendanceInactivityAlert } from './methods/viewAttendanceInactivityAlert';
import { updateAttendanceInactivityAlert } from './methods/updateAttendanceInactivityAlert';
import { checkWorkerOpenConversations } from './methods/checkWorkerOpenConversations';
import { createExternalConnectionLink } from './methods/createExternalConnectionLink';
import { viewExternalConnection } from './methods/viewExternalConnection';
import { requestExternalConnectionQrCode } from './methods/requestExternalConnectionQrCode';

@injectable()
class WorkerController {
  public createWorker = createWorker;
  public listWorker = listWorker;
  public listWorkerServers = listWorkerServers;
  public updateWorker = updateWorker;
  public viewWorker = viewWorker;
  public deleteWorker = deleteWorker;
  public changeStatusConnection = changeStatusConnection;
  public workerConnectionLogs = workerConnectionLogs;
  public recreateWorker = recreateWorker;
  public resetWorkerConnection = resetWorkerConnection;
  public uploadProfileStatus = uploadProfileStatus;
  public listProfileStatus = listProfileStatus;
  public updateProfileStatus = updateProfileStatus;
  public deleteProfileStatus = deleteProfileStatus;
  public uploadProfileInfo = uploadProfileInfo;
  public viewProfileInfo = viewProfileInfo;
  public viewWorkerConfig = viewWorkerConfig;
  public updateWorkerConfig = updateWorkerConfig;
  public updateTransferProtocolText = updateTransferProtocolText;
  public viewTransferProtocolText = viewTransferProtocolText;
  public updateTransferProtocolSectorText = updateTransferProtocolSectorText;
  public viewTransferProtocolSectorText = viewTransferProtocolSectorText;
  public updateTransferProtocolSectorAndUserText =
    updateTransferProtocolSectorAndUserText;
  public viewTransferProtocolSectorAndUserText =
    viewTransferProtocolSectorAndUserText;
  public updateStartProtocolText = updateStartProtocolText;
  public viewStartProtocolText = viewStartProtocolText;
  public updateSimultaneousAttendance = updateSimultaneousAttendance;
  public viewSimultaneousAttendance = viewSimultaneousAttendance;
  public updateTypingSimulation = updateTypingSimulation;
  public viewTypingSimulation = viewTypingSimulation;
  public updateShowMessageOnCall = updateShowMessageOnCall;
  public viewShowMessageOnCall = viewShowMessageOnCall;
  public updateSendMessageOnFinishAttendance =
    updateSendMessageOnFinishAttendance;
  public viewSendMessageOnFinishAttendance = viewSendMessageOnFinishAttendance;
  public updateChatbot = updateChatbot;
  public viewChatbot = viewChatbot;
  public viewAiAgentConfig = viewAiAgentConfig;
  public updateAiAgentConfig = updateAiAgentConfig;
  public viewAttendanceHours = viewAttendanceHours;
  public updateAttendanceHours = updateAttendanceHours;
  public viewAttendanceInactivityAlert = viewAttendanceInactivityAlert;
  public updateAttendanceInactivityAlert = updateAttendanceInactivityAlert;
  public checkWorkerOpenConversations = checkWorkerOpenConversations;
  public createExternalConnectionLink = createExternalConnectionLink;
  public viewExternalConnection = viewExternalConnection;
  public requestExternalConnectionQrCode = requestExternalConnectionQrCode;
}

export default WorkerController;
