sonar.projectKey=underchat
sonar.projectName=Underchat
sonar.projectVersion=1.0
sonar.sources=apps, packages
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/**/Dockerfile
sonar.coverage.exclusions=**
sonar.cpd.exclusions=**
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.language=ts
sonar.host.url=https://sonarqube.devunder.com/
sonar.token=sqp_0eb855bb914b2f91851b5c58586414b4f00a0983