sonar.projectKey=underchat
sonar.projectName=Underchat
sonar.projectVersion=1.0
sonar.sources=apps, packages
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/**/Dockerfile
sonar.coverage.exclusions=**
sonar.cpd.exclusions=**
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.language=ts
sonar.host.url=https://sonar.devunder.com/
sonar.token=sqp_0844b210683156f920ce05be0db225e3b1e4fc42