sonar.projectKey=underchat
sonar.projectName=Underchat
sonar.projectVersion=1.0
sonar.sources=apps, packages
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/**/Dockerfile
sonar.coverage.exclusions=**
sonar.cpd.exclusions=**
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.language=ts
sonar.host.url=https://sonar.devunder.com/
sonar.token=sqp_1853eecfc46e52a639b1016daac379351986b736