import { escapeShellSingleQuotes } from './escapeShellSingleQuotes';

export const appEnvVarsToRemove = [
  'ATLAS_PRODUCTION_SERVICE_PORT',
  'ATLAS_PRODUCTION_SERVICE_PORT_80_TCP',
  'ATLAS_PRODUCTION_SERVICE_PORT_80_TCP_ADDR',
  'ATLAS_PRODUCTION_SERVICE_PORT_80_TCP_PORT',
  'ATLAS_PRODUCTION_SERVICE_PORT_80_TCP_PROTO',
  'ATLAS_PRODUCTION_SERVICE_SERVICE_HOST',
  'ATLAS_PRODUCTION_SERVICE_SERVICE_PORT',
  'ATLAS_PRODUCTION_SERVICE_SERVICE_PORT_APP',
  'CHROME_BIN',
  'CHROME_CRASHPAD_DATABASE_PATH',
  'CHROME_PATH',
  'CONFIG_HASH',
  'CRASH_REPORTER_DISABLE',
  'DEVTRON_APP_NAME',
  'DEVTRON_CONTAINER_REPO',
  'DEVTRON_CONTAINER_TAG',
  'DEVTRON_TOKEN',
  'HOSTNAME',
  'HOME',
  'KUBERNETES_PORT',
  'KUBERNETES_PORT_443_TCP',
  'KUBERNETES_PORT_443_TCP_ADDR',
  'KUBERNETES_PORT_443_TCP_PORT',
  'KUBERNETES_PORT_443_TCP_PROTO',
  'KUBERNETES_SERVICE_HOST',
  'KUBERNETES_SERVICE_PORT',
  'KUBERNETES_SERVICE_PORT_HTTPS',
  'MANAGER_PRODUCTION_SERVICE_PORT',
  'MANAGER_PRODUCTION_SERVICE_PORT_80_TCP',
  'MANAGER_PRODUCTION_SERVICE_PORT_80_TCP_ADDR',
  'MANAGER_PRODUCTION_SERVICE_PORT_80_TCP_PORT',
  'MANAGER_PRODUCTION_SERVICE_PORT_80_TCP_PROTO',
  'MANAGER_PRODUCTION_SERVICE_SERVICE_HOST',
  'MANAGER_PRODUCTION_SERVICE_SERVICE_PORT',
  'MANAGER_PRODUCTION_SERVICE_SERVICE_PORT_APP',
  'NODE_ENV',
  'NODE_EXTRA_CA_CERTS',
  'NODE_OPTIONS',
  'OTEL_TRACES_SAMPLER',
  'OTEL_TRACES_SAMPLER_ARG',
  'POD_NAME',
  'PUBLIC_PRODUCTION_SERVICE_PORT',
  'PUBLIC_PRODUCTION_SERVICE_PORT_80_TCP',
  'PUBLIC_PRODUCTION_SERVICE_PORT_80_TCP_ADDR',
  'PUBLIC_PRODUCTION_SERVICE_PORT_80_TCP_PORT',
  'PUBLIC_PRODUCTION_SERVICE_PORT_80_TCP_PROTO',
  'PUBLIC_PRODUCTION_SERVICE_SERVICE_HOST',
  'PUBLIC_PRODUCTION_SERVICE_SERVICE_PORT',
  'PUBLIC_PRODUCTION_SERVICE_SERVICE_PORT_APP',
  'PUPPETEER_EXECUTABLE_PATH',
  'PUPPETEER_SKIP_CHROMIUM_DOWNLOAD',
  'PUPPETEER_USER_DATA_DIR',
  'PWD',
  'S3_BUCKET_PREFIX_BACKUP',
  'SASL_MECHANISM',
  'SCHEDULE_PRODUCTION_SERVICE_PORT',
  'SCHEDULE_PRODUCTION_SERVICE_PORT_80_TCP',
  'SCHEDULE_PRODUCTION_SERVICE_PORT_80_TCP_ADDR',
  'SCHEDULE_PRODUCTION_SERVICE_PORT_80_TCP_PORT',
  'SCHEDULE_PRODUCTION_SERVICE_PORT_80_TCP_PROTO',
  'SCHEDULE_PRODUCTION_SERVICE_SERVICE_HOST',
  'SCHEDULE_PRODUCTION_SERVICE_SERVICE_PORT',
  'SCHEDULE_PRODUCTION_SERVICE_SERVICE_PORT_APP',
  'SECRET_HASH',
  'SERVICE_PRODUCTION_SERVICE_PORT',
  'SERVICE_PRODUCTION_SERVICE_PORT_80_TCP',
  'SERVICE_PRODUCTION_SERVICE_PORT_80_TCP_ADDR',
  'SERVICE_PRODUCTION_SERVICE_PORT_80_TCP_PORT',
  'SERVICE_PRODUCTION_SERVICE_PORT_80_TCP_PROTO',
  'SERVICE_PRODUCTION_SERVICE_SERVICE_HOST',
  'SERVICE_PRODUCTION_SERVICE_SERVICE_PORT',
  'SERVICE_PRODUCTION_SERVICE_SERVICE_PORT_APP',
  'TMPDIR',
  'TZ',
  'VIPSHOME',
  'WEB_PRODUCTION_SERVICE_PORT',
  'WEB_PRODUCTION_SERVICE_PORT_80_TCP',
  'WEB_PRODUCTION_SERVICE_PORT_80_TCP_ADDR',
  'WEB_PRODUCTION_SERVICE_PORT_80_TCP_PORT',
  'WEB_PRODUCTION_SERVICE_PORT_80_TCP_PROTO',
  'WEB_PRODUCTION_SERVICE_SERVICE_HOST',
  'WEB_PRODUCTION_SERVICE_SERVICE_PORT',
  'WEB_PRODUCTION_SERVICE_SERVICE_PORT_APP',
  'XDG_CACHE_HOME',
  'XDG_CONFIG_HOME',
  'XDG_DATA_HOME',
  'XDG_RUNTIME_DIR',
] as const;

function escapeForSedPattern(value: string): string {
  return value.replaceAll(/[[\]{}()*+?.\\^$|/]/g, String.raw`\$&`);
}

export function getRemoveEnvVarsFromFileCommand(
  envFilePath: string,
  envVars: readonly string[] = appEnvVarsToRemove
): string {
  if (envVars.length === 0) {
    return ':';
  }

  const escapedPath = escapeShellSingleQuotes(envFilePath);
  const deleteExpressions = envVars
    .map((envVar) => `-e '/^${escapeForSedPattern(envVar)}=/d'`)
    .join(' ');

  return `sed -i ${deleteExpressions} '${escapedPath}'`;
}

export function getUpsertEnvVarInFileCommand(
  envFilePath: string,
  key: string,
  value: string
): string {
  if (!key) {
    return ':';
  }

  const escapedPath = escapeShellSingleQuotes(envFilePath);
  const escapedKeyPattern = escapeForSedPattern(key);
  const escapedKeyValue = escapeShellSingleQuotes(`${key}=${value}`);

  return `sed -i -e '/^${escapedKeyPattern}=/d' '${escapedPath}' && printf '%s\\n' '${escapedKeyValue}' >> '${escapedPath}'`;
}
