import { colors } from '../../theme/colors';

export const selectTokens = {
  fieldHeight: 48,
  fieldRadius: 12,
  fieldBorderColor: colors.grey300,
  fieldBorderColorDisabled: colors.grey200,
  fieldBackground: colors.surface,
  fieldPaddingHorizontal: 14,
  fieldLabelSize: 12,
  fieldLabelColor: colors.grey700,
  valueSize: 14,
  valueColor: colors.onSurface,
  placeholderColor: colors.grey500,
  sheetOverlayColor: 'rgba(0,0,0,0.38)',
  sheetRadius: 18,
  sheetBackground: colors.surface,
  sheetPadding: 14,
  sheetMaxHeightPercent: '78%' as const,
  optionMinHeight: 48,
  optionHorizontalPadding: 14,
  optionDividerColor: colors.grey200,
  optionSelectedBg: 'rgba(40, 101, 183, 0.08)',
  optionPressedBg: 'rgba(40, 101, 183, 0.05)',
  actionTextColor: colors.primary,
  searchInputHeight: 42,
  searchInputRadius: 10,
  searchInputBg: colors.inputBg,
} as const;
