export const OFFICIAL_WHATSAPP_INTERACTIVE_LIMITS = Object.freeze({
  headerText: 60,
  bodyText: 1024,
  footerText: 60,
  listButtonText: 20,
  listSectionTitle: 24,
  listRowId: 200,
  listRowTitle: 24,
  listRowDescription: 72,
  listTotalRows: 10,
  replyButtons: 3,
  replyButtonId: 256,
  replyButtonTitle: 20,
  ctaUrlDisplayText: 20,
  flowCta: 30,
  productListSectionTitle: 24,
  productListSections: 10,
  productListItems: 30,
} as const);
