export enum EChatPermissions {
  chat_group = 'chat_group',
  chat_access = 'chat_access',
  view_chat_attendants_info = 'view_chat_attendants_info',
  preview_chat = 'preview_chat',
  list_all_chats_in_sector = 'list_all_chats_in_sector',
  pick_queue_chat = 'pick_queue_chat',
  list_all_chats_without_sector_limit = 'list_all_chats_without_sector_limit',
  view_chatbot_messages = 'view_chatbot_messages',
  close_chat_without_attending = 'close_chat_without_attending',
  manage_in_chat_lifecycle = 'manage_in_chat_lifecycle',
  reopen_chat = 'reopen_chat',
  disable_send_message_on_finish_attendance = 'disable_send_message_on_finish_attendance',
  attendance_history = 'attendance_history',
  forward_to_output_chatbot = 'forward_to_output_chatbot',
  generate_message_with_ai = 'generate_message_with_ai',
  chat_kanban = 'chat_kanban',
}
