import { FastifyInstance } from 'fastify';
import authRoutes from '@/routes/auth.route';
import serverRoutes from '@/routes/server.route';
import healthRoutes from '@/routes/health.route';
import centrifugoRoutes from '@/routes/centrifugo.route';
import roleRoutes from './role.route';
import workerRoutes from '@/routes/worker.route';
import chatRoutes from '@/routes/chat.route';
import sectorRoutes from './sector.route';
import userRoutes from './user.route';
import zipcodeRoutes from './zipcode.route';
import accountRoutes from './account.route';
import planRoutes from './plan.route';
import planCrossSellRoutes from './planCrossSell.route';
import messageTemplateRoutes from './messageTemplate.route';
import labelTemplateRoutes from './labelTemplate.route';
import contactRoutes from './contact.route';
import contactGroupRoutes from './contactGroup.route';
import permissionRoutes from './permission.route';
import presenceRoutes from './presence.route';

export default function registerRoutes(server: FastifyInstance) {
  server.register(authRoutes);
  server.register(healthRoutes);
  server.register(serverRoutes);
  server.register(centrifugoRoutes);
  server.register(roleRoutes);
  server.register(workerRoutes);
  server.register(chatRoutes);
  server.register(sectorRoutes);
  server.register(userRoutes);
  server.register(zipcodeRoutes);
  server.register(accountRoutes);
  server.register(planRoutes);
  server.register(planCrossSellRoutes);
  server.register(messageTemplateRoutes);
  server.register(labelTemplateRoutes);
  server.register(contactRoutes);
  server.register(contactGroupRoutes);
  server.register(permissionRoutes);
  server.register(presenceRoutes);
}
