import { FastifyInstance } from 'fastify';
import authRoutes from '@/routes/auth.route';
import regRoutes from '@/routes/register.route';
import serverRoutes from '@/routes/server.route';
import healthRoutes from '@/routes/health.route';
import centrifugoRoutes from '@/routes/centrifugo.route';
import roleRoutes from './role.route';
import workerRoutes from '@/routes/worker.route';
import chatRoutes from '@/routes/chat.route';
import chatbotRoutes from '@/routes/chatbot.route';
import sectorRoutes from './sector.route';
import userRoutes from './user.route';
import zipcodeRoutes from './zipcode.route';
import accountRoutes from './account.route';
import accountSettingsRoutes from './accountSettings.route';
import planRoutes from './plan.route';
import planCrossSellRoutes from './planCrossSell.route';
import messageTemplateRoutes from './messageTemplate.route';
import labelTemplateRoutes from './labelTemplate.route';
import contactRoutes from './contact.route';
import contactGroupRoutes from './contactGroup.route';
import permissionRoutes from './permission.route';
import expenditureRoutes from './expenditure.route';
import financialReportRoutes from './financialReport.route';
import reportConversationHistoryRoutes from './reportConversationHistory.route';
import reportAttendanceRoutes from './reportAttendance.route';
import configRoutes from './config.route';
import webhookRoutes from './webhook.route';
import dashboardRoutes from './dashboard.route';
import scheduleRoutes from './schedule.route';
import reportSalesRoutes from './reportSales.route';
import reportClientsRoutes from './reportClients.route';
import reportUsersRoutes from './reportUsers.route';
import masterSessionRoutes from './masterSession.route';
import aiAgentRoutes from './aiAgent.route';
import pushRoutes from './push.route';
import releaseRoutes from './release.route';

export default function registerRoutes(server: FastifyInstance) {
  server.register(authRoutes);
  server.register(healthRoutes);
  server.register(serverRoutes);
  server.register(centrifugoRoutes);
  server.register(roleRoutes);
  server.register(workerRoutes);
  server.register(chatRoutes);
  server.register(chatbotRoutes);
  server.register(sectorRoutes);
  server.register(userRoutes);
  server.register(zipcodeRoutes);
  server.register(accountRoutes);
  server.register(accountSettingsRoutes);
  server.register(planRoutes);
  server.register(planCrossSellRoutes);
  server.register(messageTemplateRoutes);
  server.register(labelTemplateRoutes);
  server.register(contactRoutes);
  server.register(contactGroupRoutes);
  server.register(permissionRoutes);
  server.register(expenditureRoutes);
  server.register(financialReportRoutes);
  server.register(reportConversationHistoryRoutes);
  server.register(reportAttendanceRoutes);
  server.register(configRoutes);
  server.register(webhookRoutes);
  server.register(dashboardRoutes);
  server.register(scheduleRoutes);
  server.register(reportSalesRoutes);
  server.register(reportClientsRoutes);
  server.register(reportUsersRoutes);
  server.register(masterSessionRoutes);
  server.register(aiAgentRoutes);
  server.register(pushRoutes);
  server.register(releaseRoutes);
  server.register(regRoutes);
}
