import { injectable } from 'tsyringe';
import { listNotifications } from '@/controllers/notifications/methods/listNotifications';
import { updateNotifications } from '@/controllers/notifications/methods/updateNotifications';
import { listWorkers } from '@/controllers/notifications/methods/listWorkers';
import { listSentNotifications } from '@/controllers/notifications/methods/listSentNotifications';
import { listNfse } from './methods/listNfse';
import { updateNfse } from './methods/updateNfse';
import { updateNfseIntegration } from './methods/updateNfseIntegration';
import { uploadNfseCertificate } from './methods/uploadNfseCertificate';
import { listChannels } from './methods/listChannels';
import { listAccounts } from './methods/listAccounts';
import { listChannelServers } from './methods/listChannelServers';
import { recreateChannel } from './methods/recreateChannel';
import { deleteChannel } from './methods/deleteChannel';
import { recreateChannelsAll } from './methods/recreateChannelsAll';
import { channelsStatistics } from './methods/channelsStatistics';
import { listCreditCardFee } from './methods/listCreditCardFee';
import { updateCreditCardFee } from './methods/updateCreditCardFee';
import { checkChannelOpenConversations } from './methods/checkChannelOpenConversations';
import { listMethodPayments } from './methods/listMethodPayments';
import { updateMethodPayment } from './methods/updateMethodPayment';
import { updateChannel } from './methods/updateChannel';
import { listS3BackupUploads } from './methods/listS3BackupUploads';
import { reprocessS3BackupUpload } from './methods/reprocessS3BackupUpload';
import { listWarmChannels } from './methods/listWarmChannels';
import { listWarmChannelServers } from './methods/listWarmChannelServers';
import { recreateWarmChannel } from './methods/recreateWarmChannel';
import { recreateWarmChannelsAll } from './methods/recreateWarmChannelsAll';
import { viewWarmChannelSettings } from './methods/viewWarmChannelSettings';
import { updateWarmChannelSettings } from './methods/updateWarmChannelSettings';

@injectable()
class ConfigController {
  public listNotifications = listNotifications;
  public updateNotifications = updateNotifications;
  public listWorkers = listWorkers;
  public listSentNotifications = listSentNotifications;
  public listNfse = listNfse;
  public updateNfse = updateNfse;
  public updateNfseIntegration = updateNfseIntegration;
  public uploadNfseCertificate = uploadNfseCertificate;
  public listChannels = listChannels;
  public listAccounts = listAccounts;
  public listChannelServers = listChannelServers;
  public recreateChannel = recreateChannel;
  public deleteChannel = deleteChannel;
  public recreateChannelsAll = recreateChannelsAll;
  public channelsStatistics = channelsStatistics;
  public updateChannel = updateChannel;
  public listCreditCardFee = listCreditCardFee;
  public updateCreditCardFee = updateCreditCardFee;
  public checkChannelOpenConversations = checkChannelOpenConversations;
  public listMethodPayments = listMethodPayments;
  public updateMethodPayment = updateMethodPayment;
  public listS3BackupUploads = listS3BackupUploads;
  public reprocessS3BackupUpload = reprocessS3BackupUpload;
  public listWarmChannels = listWarmChannels;
  public listWarmChannelServers = listWarmChannelServers;
  public recreateWarmChannel = recreateWarmChannel;
  public recreateWarmChannelsAll = recreateWarmChannelsAll;
  public viewWarmChannelSettings = viewWarmChannelSettings;
  public updateWarmChannelSettings = updateWarmChannelSettings;
}

export default ConfigController;
