import { injectable } from 'tsyringe';
import { listChats } from './methods/listChats';
import { updateChatsUser } from './methods/updateChatsUser';
import { listMessageChats } from './methods/listMessageChats';
import { createMessageChats } from './methods/createMessageChats';
import { viewChatLinkPreview } from './methods/viewChatLinkPreview';
import { reactMessage } from './methods/reactMessage';
import { deleteMessage } from './methods/deleteMessage';
import { editMessage } from './methods/editMessage';
import { updateChatStatus } from './methods/updateChatStatus';
import { clearChatSummary } from './methods/clearChatSummary';
import { startChatWithContact } from './methods/startChatWithContact';
import { searchMessages } from './methods/searchMessages';
import { transferChat } from './methods/transferChat';
import { searchChats } from './methods/searchChats';
import { viewWorkerConfigForChat } from './methods/viewWorkerConfigForChat';
import { listTransferOptions } from './methods/listTransferOptions';
import { listTransferUsers } from './methods/listTransferUsers';
import { listTransferSectors } from './methods/listTransferSectors';
import { listTransferSectorUsers } from './methods/listTransferSectorUsers';
import { listContacts } from './methods/listContacts';
import { viewContact } from './methods/viewContact';
import { viewContactEmail } from './methods/viewContactEmail';
import { viewContactPhone } from './methods/viewContactPhone';
import { listLabelTemplates } from './methods/listLabelTemplates';
import { createContact } from './methods/createContact';
import { updateContact } from './methods/updateContact';
import { deleteContactPhoto } from './methods/deleteContactPhoto';
import { validateContact } from './methods/validateContact';
import { listQuickMessageTemplates } from './methods/listQuickMessageTemplates';
import { updateChatLabel } from './methods/updateChatLabel';

@injectable()
class ChatController {
  public listChats = listChats;
  public listMessageChats = listMessageChats;
  public updateChatsUser = updateChatsUser;
  public createMessageChats = createMessageChats;
  public viewChatLinkPreview = viewChatLinkPreview;
  public reactMessage = reactMessage;
  public deleteMessage = deleteMessage;
  public editMessage = editMessage;
  public updateChatStatus = updateChatStatus;
  public clearChatSummary = clearChatSummary;
  public startChatWithContact = startChatWithContact;
  public searchMessages = searchMessages;
  public transferChat = transferChat;
  public searchChats = searchChats;
  public viewWorkerConfigForChat = viewWorkerConfigForChat;
  public listTransferOptions = listTransferOptions;
  public listTransferUsers = listTransferUsers;
  public listTransferSectors = listTransferSectors;
  public listTransferSectorUsers = listTransferSectorUsers;
  public listContacts = listContacts;
  public viewContact = viewContact;
  public viewContactEmail = viewContactEmail;
  public viewContactPhone = viewContactPhone;
  public listLabelTemplates = listLabelTemplates;
  public createContact = createContact;
  public updateContact = updateContact;
  public deleteContactPhoto = deleteContactPhoto;
  public validateContact = validateContact;
  public listQuickMessageTemplates = listQuickMessageTemplates;
  public updateChatLabel = updateChatLabel;
}

export default ChatController;
