import { injectable } from 'tsyringe';
import { assignUserRole } from './methods/assignUserRole';
import { blockUser } from './methods/blockUser';
import { createUser } from './methods/createUser';
import { deletePhoto } from './methods/deletePhoto';
import { deleteUser } from './methods/deleteUser';
import { editUser } from './methods/editUser';
import { listAllUsers } from './methods/listAllUsers';
import { listUser } from './methods/listUser';
import { listUserAccounts } from './methods/listUserAccounts';
import { listUserChannels } from './methods/listUserChannels';
import { listUserRoles } from './methods/listUserRoles';
import { listUserSectors } from './methods/listUserSectors';
import { sessionLogin } from './methods/sessionLogin';
import { unblockUser } from './methods/unblockUser';
import { updateAttendanceHours } from './methods/updateAttendanceHours';
import { uploadPhoto } from './methods/uploadPhoto';
import { viewAttendanceHours } from './methods/viewAttendanceHours';
import { viewAttendanceHoursStatus } from './methods/viewAttendanceHoursStatus';
import { viewUser } from './methods/viewUser';
import { viewUserAddress1 } from './methods/viewUserAddress1';
import { viewUserAddress2 } from './methods/viewUserAddress2';
import { viewUserChannels } from './methods/viewUserChannels';
import { viewUserDocument } from './methods/viewUserDocument';
import { viewUserEmail } from './methods/viewUserEmail';
import { viewUserPhone } from './methods/viewUserPhone';
import { viewUserRole } from './methods/viewUserRole';
import { viewUserSectors } from './methods/viewUserSectors';

@injectable()
class UserController {
  public listUser = listUser;
  public listAllUsers = listAllUsers;
  public viewUser = viewUser;
  public viewUserPhone = viewUserPhone;
  public viewUserEmail = viewUserEmail;
  public viewUserDocument = viewUserDocument;
  public viewUserAddress1 = viewUserAddress1;
  public viewUserAddress2 = viewUserAddress2;
  public deleteUser = deleteUser;
  public updateUser = editUser;
  public createUser = createUser;
  public assignUserRole = assignUserRole;
  public viewUserRole = viewUserRole;
  public uploadPhoto = uploadPhoto;
  public deletePhoto = deletePhoto;
  public listUserRoles = listUserRoles;
  public listUserSectors = listUserSectors;
  public viewUserSectors = viewUserSectors;
  public listUserChannels = listUserChannels;
  public viewUserChannels = viewUserChannels;
  public listUserAccounts = listUserAccounts;
  public sessionLogin = sessionLogin;
  public viewAttendanceHours = viewAttendanceHours;
  public updateAttendanceHours = updateAttendanceHours;
  public viewAttendanceHoursStatus = viewAttendanceHoursStatus;
  public blockUser = blockUser;
  public unblockUser = unblockUser;
}

export default UserController;
