-- Create "user_status" table
CREATE TABLE "user_status" (
  "user_status_id" smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying(20) NOT NULL,
  "created_at" timestamptz NULL DEFAULT now(),
  "updated_at" timestamptz NULL DEFAULT now(),
  PRIMARY KEY ("user_status_id")
);
-- Create "user_type" table
CREATE TABLE "user_type" (
  "user_type_id" smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying(20) NOT NULL,
  "created_at" timestamptz NULL DEFAULT now(),
  "updated_at" timestamptz NULL DEFAULT now(),
  PRIMARY KEY ("user_type_id")
);
-- Create "user" table
CREATE TABLE "user" (
  "user_id" smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_status_id" smallint NOT NULL,
  "user_type_id" smallint NOT NULL,
  "username" character varying(50) NULL,
  "email" character varying(100) NOT NULL,
  "password" character varying(255) NOT NULL,
  "created_at" timestamptz NULL DEFAULT now(),
  "updated_at" timestamptz NULL DEFAULT now(),
  "deleted_at" timestamptz NULL,
  PRIMARY KEY ("user_id"),
  CONSTRAINT "user_user_status_id_user_status_user_status_id_fk" FOREIGN KEY ("user_status_id") REFERENCES "user_status" ("user_status_id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "user_user_type_id_user_type_user_type_id_fk" FOREIGN KEY ("user_type_id") REFERENCES "user_type" ("user_type_id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "user_address" table
CREATE TABLE "user_address" (
  "user_address_id" smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" smallint NOT NULL,
  "zip_code" character varying(10) NOT NULL,
  "street" character varying(100) NOT NULL,
  "number" character varying(10) NOT NULL,
  "neighborhood" character varying(50) NOT NULL,
  "city" character varying(50) NOT NULL,
  "state" character varying(50) NOT NULL,
  "complement" character varying(100) NULL,
  "created_at" timestamptz NULL DEFAULT now(),
  "updated_at" timestamptz NULL DEFAULT now(),
  "deleted_at" timestamptz NULL,
  PRIMARY KEY ("user_address_id"),
  CONSTRAINT "user_address_user_id_user_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "user" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "user_document_type" table
CREATE TABLE "user_document_type" (
  "user_document_type_id" smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying(20) NOT NULL,
  "created_at" timestamptz NULL DEFAULT now(),
  "updated_at" timestamptz NULL DEFAULT now(),
  PRIMARY KEY ("user_document_type_id")
);
-- Create "user_document" table
CREATE TABLE "user_document" (
  "user_document_id" smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_document_type_id" smallint NOT NULL,
  "document" character varying(20) NOT NULL,
  "created_at" timestamptz NULL DEFAULT now(),
  "updated_at" timestamptz NULL DEFAULT now(),
  PRIMARY KEY ("user_document_id"),
  CONSTRAINT "user_document_user_document_type_id_user_document_type_user_doc" FOREIGN KEY ("user_document_type_id") REFERENCES "user_document_type" ("user_document_type_id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "user_info" table
CREATE TABLE "user_info" (
  "user_info_id" smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" smallint NOT NULL,
  "phone" character varying(20) NULL,
  "photo" character varying(255) NULL,
  "name" character varying(100) NOT NULL,
  "last_name" character varying(100) NOT NULL,
  "birth_date" timestamptz NULL,
  "created_at" timestamptz NULL DEFAULT now(),
  "updated_at" timestamptz NULL DEFAULT now(),
  "deleted_at" timestamptz NULL,
  PRIMARY KEY ("user_info_id"),
  CONSTRAINT "user_info_user_id_user_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "user" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
