-- Create "worker_status" table
CREATE TABLE "worker_status" (
  "worker_status_id" smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "status" character varying(500) NULL,
  "created_at" timestamptz NULL DEFAULT now(),
  "updated_at" timestamptz NULL DEFAULT now(),
  PRIMARY KEY ("worker_status_id")
);
-- Create "worker_type" table
CREATE TABLE "worker_type" (
  "worker_type_id" smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "type" character varying(500) NULL,
  "created_at" timestamptz NULL DEFAULT now(),
  "updated_at" timestamptz NULL DEFAULT now(),
  PRIMARY KEY ("worker_type_id")
);
-- Create "worker" table
CREATE TABLE "worker" (
  "worker_id" smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "worker_status_id" smallint NOT NULL,
  "worker_type_id" smallint NOT NULL,
  "server_id" smallint NOT NULL,
  "account_id" smallint NOT NULL,
  "name" character varying(50) NOT NULL,
  "container_id" character varying(100) NOT NULL,
  "created_at" timestamptz NULL DEFAULT now(),
  "updated_at" timestamptz NULL DEFAULT now(),
  "deleted_at" timestamptz NULL,
  PRIMARY KEY ("worker_id"),
  CONSTRAINT "worker_account_id_account_account_id_fk" FOREIGN KEY ("account_id") REFERENCES "account" ("account_id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "worker_server_id_server_server_id_fk" FOREIGN KEY ("server_id") REFERENCES "server" ("server_id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "worker_worker_status_id_worker_status_worker_status_id_fk" FOREIGN KEY ("worker_status_id") REFERENCES "worker_status" ("worker_status_id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "worker_worker_type_id_worker_type_worker_type_id_fk" FOREIGN KEY ("worker_type_id") REFERENCES "worker_type" ("worker_type_id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
