-- Create "plan_product" table
CREATE TABLE "plan_product" (
  "plan_product_id" smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying(500) NULL,
  "created_at" timestamptz NULL DEFAULT now(),
  "updated_at" timestamptz NULL DEFAULT now(),
  PRIMARY KEY ("plan_product_id")
);
-- Create "plan_cross_sell" table
CREATE TABLE "plan_cross_sell" (
  "plan_cross_sell_id" smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "plan_product_id" smallint NOT NULL,
  "quantity" smallint NOT NULL,
  "price" numeric(10,2) NOT NULL,
  "created_at" timestamptz NULL DEFAULT now(),
  "updated_at" timestamptz NULL DEFAULT now(),
  "deleted_at" timestamptz NULL,
  PRIMARY KEY ("plan_cross_sell_id"),
  CONSTRAINT "plan_cross_sell_plan_product_id_plan_product_plan_product_id_fk" FOREIGN KEY ("plan_product_id") REFERENCES "plan_product" ("plan_product_id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "plan_cross_sell_account" table
CREATE TABLE "plan_cross_sell_account" (
  "plan_cross_sell_account_id" smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "plan_cross_sell_id" smallint NOT NULL,
  "account_id" smallint NOT NULL,
  "created_at" timestamptz NULL DEFAULT now(),
  "updated_at" timestamptz NULL DEFAULT now(),
  "deleted_at" timestamptz NULL,
  PRIMARY KEY ("plan_cross_sell_account_id"),
  CONSTRAINT "plan_cross_sell_account_account_id_account_account_id_fk" FOREIGN KEY ("account_id") REFERENCES "account" ("account_id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "plan_cross_sell_account_plan_cross_sell_id_plan_cross_sell_plan" FOREIGN KEY ("plan_cross_sell_id") REFERENCES "plan_cross_sell" ("plan_cross_sell_id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "plan" table
CREATE TABLE "plan" (
  "plan_id" smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying(50) NOT NULL,
  "price" numeric(10,2) NOT NULL,
  "price_old" numeric(10,2) NOT NULL,
  "created_at" timestamptz NULL DEFAULT now(),
  "updated_at" timestamptz NULL DEFAULT now(),
  "deleted_at" timestamptz NULL,
  PRIMARY KEY ("plan_id")
);
-- Create "plan_items" table
CREATE TABLE "plan_items" (
  "plan_item_id" smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "plan_product_id" smallint NOT NULL,
  "plan_id" smallint NOT NULL,
  "quantity" smallint NOT NULL,
  "created_at" timestamptz NULL DEFAULT now(),
  "updated_at" timestamptz NULL DEFAULT now(),
  "deleted_at" timestamptz NULL,
  PRIMARY KEY ("plan_item_id"),
  CONSTRAINT "plan_items_plan_id_plan_plan_id_fk" FOREIGN KEY ("plan_id") REFERENCES "plan" ("plan_id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "plan_items_plan_product_id_plan_product_plan_product_id_fk" FOREIGN KEY ("plan_product_id") REFERENCES "plan_product" ("plan_product_id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
