export enum EElasticIndex {
  install_server = 'install-server',
  wpp_connection = 'wpp-connection',
  chat = 'chat',
  message = 'message',
  chatbot_flow = 'chatbot-flow',
  chatbot_flow_configurations = 'chatbot-flow-configurations',
  notification = 'notification',
  schedule = 'schedule',
  ai_agent_prompt_embedding = 'ai-agent-prompt-embedding',
  chat_history_embedding = 'chat-history-embedding',
  webhook = 'webhook',
  webhook_mapping = 'webhook-mapping',
  internal_chat_message = 'internal-chat-message',
}
