export enum EMessageType {
  text = 'text',
  mention = 'mention',
  location = 'location',
  contact_card = 'contact_card',
  contacts = 'contacts',
  react = 'react',
  pin_message = 'pin_message',
  poll = 'poll',
  image = 'image',
  video = 'video',
  audio = 'audio',
  sticker = 'sticker',
  document = 'document',
  view_once = 'view_once',
  view_once_image = 'view_once_image',
  view_once_video = 'view_once_video',
  delete_message = 'delete_message',
  edit_text = 'edit_text',
  set_disappearing_messages = 'set_disappearing_messages',
  button_reply = 'button_reply',
  list_reply = 'list_reply',
  group_invite = 'group_invite',
  product = 'product',
  status_image = 'status_image',
  status_video = 'status_video',
  status_text = 'status_text',
}
