export interface IWorkerConnectionStateProto {
  code?: number;
  status?: string;
  worker_id?: string;
  account_id?: string;
  worker_type_id?: string;
  qrcode?: string;
  is_new_login?: boolean;
  time?: number | string;
  phone?: string;
  disconnected_user?: boolean;
  pairing_code?: string;
  passkey_public_key?: string;
  passkey_pending?: boolean;
  passkey_confirmation_code?: string;
  passkey_skip_handoff_ux?: boolean;
  seconds_until_next_attempt?: number;
  worker_status_id?: string;
  attempt?: number;
  max_attempts?: number;
  connection_attempt_id?: string;
  authorized_connection_epoch?: string;
  debug_trace_id?: string;
  qr_pending?: boolean;
  qr_generated_at?: string;
  expires_at?: string;
  reason?: string;
  error?: string;
  time_to_first_qr_ms?: number | string;
  container_id?: string;
  runtime_generation?: number | string;
  warm_pool_id?: string;
  proxy_status?: string;
  proxy_error_code?: string;
  proxy_fallback?: string;
  proxy_bypassed?: boolean;
  session_ready?: boolean;
  can_send?: boolean;
  can_receive_runtime?: boolean;
  authenticated?: boolean;
  provider_state?: string;
  degraded_reason?: string;
  last_probe_at?: string;
  probe_latency_ms?: number;
  connection_status?: import('./IWhatsappConnectionStatus').IWhatsappConnectionStatus;
  connection_status_source_id?: string;
}
