export const ELEVENLABS_VOICES_PT_BR = [
  { value: '96cLX3dkyNUmTHwkNXeS', title: 'Thiago Realista' },
  { value: '36rVQA1AOIPwpA3Hg1tC', title: 'Matheus' },
  { value: 'CZD4BJ803C6T0alQxsR7', title: 'Andreia I.' },
  { value: 'Libc4Ixlrn2thn1XQaDL', title: 'Higor Bourges' },
  { value: '13auRs13gEKuqxX054G2', title: 'Gustavo Barros' },
  { value: 'NGS0ZsC7j4t4dCWbPdgO', title: 'Dhyogo Azevedo' },
  { value: 'qarDw4DEvUqP3FBlpO0T', title: 'JonOliveira' },
  { value: '29Pm0vQJJRoVfMCsUKB6', title: 'Márcio' },
  { value: 'tlcdlAx9D2VUpCZ2etQ7', title: 'Guilherme Converseiro' },
  { value: 'PZIBrGsMjLyYasEz50bI', title: 'Jennifer - Hyper-realistic' },
  { value: 'AaeZyyi87RCxtFnHPS3e', title: 'Prof. Campanholi' },
  { value: 'cQAY19cNx1hXYCYZV4ae', title: 'Deluca' },
  { value: 'nd1z1vC7yrh6u3ZztpCd', title: 'Renato' },
  { value: 'xWdpADtEio43ew1zGxUQ', title: 'Matheus Santos' },
  { value: 'IKpiSijWzlhOL6uX83EH', title: 'Will - Institucional' },
  { value: 'ojFdI32rbZHI2rxgzrEw', title: 'Nando Andrade' },
  { value: 'm151rjrbWXbBqyq56tly', title: 'Carla - Institucional' },
  { value: 'SVgp5d1fyFQRW1eQbwkq', title: 'Lucas' },
  { value: 'CbNfj17erd366KLOAufd', title: 'Guilherme Henrique' },
  { value: 'Jx7J2Fi5Ssla82TsW3YE', title: 'Cassio' },
  { value: 'y3X5crcIDtFawPx7bcNq', title: 'Eliel - Storyteller' },
  { value: 'OB6x7EbXYlhG4DDTB1XU', title: 'Michelle' },
  { value: 'eVXYtPVYB9wDoz9NVTIy', title: 'Carla' },
  { value: 'iScHbNW8K33gNo3lGgbo', title: 'Marianne' },
  { value: 'eQnBc1norhy4xHHbr9Ip', title: 'Cielo' },
  { value: 'x3mAOLD9WzlmrFCwA1S3', title: 'Evelin Perdomo' },
  { value: 'lWq4KDY8znfkV0DrK8Vb', title: 'Yasmin Alves' },
  { value: 'x8udhExu0uJxUn4Tf9Az', title: 'Slany' },
  { value: 'MZxV5lN3cv7hi1376O0m', title: 'Ana Dias' },
  { value: 'QJd9SLe6MVCdF6DR0EAu', title: 'Gabby' },
  { value: 'vibfi5nlk3hs8Mtvf9Oy', title: 'Ana - Brazilian' },
  { value: 'FIEA0c5UHH9JnvWaQrXS', title: 'Michele - Brazilian' },
  { value: 'nHNZWlqUWtEKPr3hhFQP', title: 'Daiane Candido' },
  { value: 'Eyspt3SYhZzXd1Jd3J8O', title: 'Bia - Brazilian' },
  { value: 'e70XR1sNoAGoLxPGL5f6', title: 'Márcio (alternativo)' },
  { value: '6pQlwCgfwffNdI3jjzM6', title: 'Fernando Borges' },
  { value: 'ylkAmqCrRDIZwbkOGyJe', title: 'Wlademir' },
  { value: 'UPTmB6OygMADpd4LOwE5', title: 'Vinicius Bergamo' },
  { value: 'WFSxKvz27RguNRD3Phoq', title: 'Wesley Bessa' },
  { value: 'UNlPbm2VdUhPl6lNL6D6', title: 'Diego' },
  { value: 'n2aB5UDlpf5USMJH7Qst', title: 'Gilson Lima' },
  { value: '6dHxv8ke5peKaO9xM46v', title: 'Gustavo Jannuzzi' },
  { value: 'hd5xzUNI8bF3Lvk3KkTO', title: 'Juliana Barbieri' },
  { value: 'ZxeM4498ujGNHYhQXtLS', title: 'Davi' },
  { value: 'JNI7HKGyqNaHqfihNoCi', title: 'Rener' },
  { value: 'gwiHKiILZ18I7Pb40yFN', title: 'FMDAmbrosio' },
  { value: 'hwnuNyWkl9DjdTFykrN6', title: 'Adriano - Narrator' },
  { value: 'ZAYPVq9zNssSHWCf6pko', title: 'Roberto Barbieri' },
  { value: '9pDzHy2OpOgeXM8SeL0t', title: 'Borges' },
];
