export const ELEVENLABS_VOICES_PT_BR = [
  { value: '21m00Tcm4TlvDq8ikWAM', title: 'Rachel (Free)' },
  { value: 'pNInz6obpgDQGcFmaJgB', title: 'Adam (Free)' },
  { value: 'EXAVITQu4vr4xnSDxMaL', title: 'Sarah (Free)' },
  { value: 'ErXwobaYiN019PkySvjV', title: 'Antoni (Free)' },
  { value: 'VR6AewLTigWG4xSOukaG', title: 'Arnold (Free)' },
  { value: 'onwK4e9ZLuTAKqWW03F9', title: 'Daniel (Free)' },
  { value: 'ThT5KcBeYPX3keUQqHPh', title: 'Dorothy (Free)' },
  { value: 'pMsXgVXv3BLzUgSXRplE', title: 'Serena (Free)' },
  { value: 'XrExE9yKIg1WjnnlVkGX', title: 'Matilda (Free)' },
  { value: 'jsCqWAovK2LkecY7zXl4', title: 'Freya (Free)' },
  { value: 'XB0fDUnXU5powFXDhCwa', title: 'Charlotte (Free)' },
  { value: 'z9fAnlkpzviPz146aGWa', title: 'Glinda (Free)' },
  { value: 'oWAxZDx7w5VEj9dCyTzz', title: 'Grace (Free)' },
  { value: 'LcfcDJNUP1GQjkzn1xUU', title: 'Emily (Free)' },
  { value: 'GBv7mTt0atIp3Br8iCZE', title: 'Thomas (Free)' },
  { value: 'AZnzlk1XvdvUeBnXmlld', title: 'Domi (Free)' },
  { value: 'jBpfuIE2acCO8z3wKNLl', title: 'Gigi (Free)' },
  { value: 'zcAOhNBS3c14rBihAFp1', title: 'Giovanni (Free)' },
  { value: 'piTKgcLEGmPE4e6mEKli', title: 'Nicole (Free)' },
  { value: 'flq6f7yk4E4fJM5XTYuZ', title: 'Michael (Free)' },
  { value: 'pqHfZKP75CvOlQylNhV4', title: 'Bill (Free)' },
  { value: 'nPczCjzI2devNBz1zQrb', title: 'Brian (Free)' },
  { value: 'IKne3meq5aSn9XLyUdCD', title: 'Charlie (Free)' },
  { value: 'iP95p4xoKVk53GoZ742B', title: 'Chris (Free)' },
  { value: '2EiwWnXFnvU5JabPnv8n', title: 'Clyde (Free)' },
  { value: 'N2lVS1w4EtoT3dr4eOWO', title: 'Callum (Free)' },
  { value: 'CYw3kZ02Hs0563khs1Fj', title: 'Dave (Free)' },
  { value: '29vD33N1CtxCmqQRPOHJ', title: 'Drew (Free)' },
  { value: 'g5CIjZEefAph4nQFvHAz', title: 'Ethan (Free)' },
  { value: 'D38z5RcWu1voky8WS1ja', title: 'Fin (Free)' },
  { value: 'JBFqnCBsd6RMkjVDRZzb', title: 'George (Free)' },
  { value: 'SOYHLrjzK2X1ezoPC6cr', title: 'Harry (Free)' },
  { value: 'ZQe5CZNOzWyzPSCn5a3c', title: 'James (Free)' },
  { value: 'bVMeCyTHy58xNoL34h3p', title: 'Jeremy (Free)' },
  { value: 't0jbNlBVZ17f02VDIeMI', title: 'Jessie (Free)' },
  { value: 'Zlb1dXrM653N07WRdFW3', title: 'Joseph (Free)' },
  { value: 'TxGEqnHWrfWFTfGW9XjX', title: 'Josh (Free)' },
  { value: 'TX3LPaxmHKxFdv7VOQHJ', title: 'Liam (Free)' },
  { value: 'pFZP5JQG7iQjIQuC4Bku', title: 'Lily (Free)' },
  { value: 'zrHiDhphv9ZnVXBqCLjz', title: 'Mimi (Free)' },
  { value: 'ODq5zmih8GrVes37Dizd', title: 'Patrick (Free)' },
  { value: '5Q0t7uMcjvnagumLfvZi', title: 'Paul (Free)' },
  { value: 'yoZ06aMxZJJ28mfd3POQ', title: 'Sam (Free)' },
  { value: 'Xb7hH8MSUJpSbSDYk0k2', title: 'Alice (Free)' },
  { value: '96cLX3dkyNUmTHwkNXeS', title: 'Thiago Realista' },
  { value: '36rVQA1AOIPwpA3Hg1tC', title: 'Matheus' },
  { value: 'CZD4BJ803C6T0alQxsR7', title: 'Andreia I.' },
  { value: 'Libc4Ixlrn2thn1XQaDL', title: 'Higor Bourges' },
  { value: '13auRs13gEKuqxX054G2', title: 'Gustavo Barros' },
  { value: 'NGS0ZsC7j4t4dCWbPdgO', title: 'Dhyogo Azevedo' },
  { value: 'qarDw4DEvUqP3FBlpO0T', title: 'JonOliveira' },
  { value: '29Pm0vQJJRoVfMCsUKB6', title: 'Márcio' },
  { value: 'tlcdlAx9D2VUpCZ2etQ7', title: 'Guilherme Converseiro' },
  { value: 'PZIBrGsMjLyYasEz50bI', title: 'Jennifer - Hyper-realistic' },
  { value: 'AaeZyyi87RCxtFnHPS3e', title: 'Prof. Campanholi' },
  { value: 'cQAY19cNx1hXYCYZV4ae', title: 'Deluca' },
  { value: 'nd1z1vC7yrh6u3ZztpCd', title: 'Renato' },
  { value: 'xWdpADtEio43ew1zGxUQ', title: 'Matheus Santos' },
  { value: 'IKpiSijWzlhOL6uX83EH', title: 'Will - Institucional' },
  { value: 'ojFdI32rbZHI2rxgzrEw', title: 'Nando Andrade' },
  { value: 'm151rjrbWXbBqyq56tly', title: 'Carla - Institucional' },
  { value: 'SVgp5d1fyFQRW1eQbwkq', title: 'Lucas' },
  { value: 'CbNfj17erd366KLOAufd', title: 'Guilherme Henrique' },
  { value: 'Jx7J2Fi5Ssla82TsW3YE', title: 'Cassio' },
  { value: 'y3X5crcIDtFawPx7bcNq', title: 'Eliel - Storyteller' },
  { value: 'OB6x7EbXYlhG4DDTB1XU', title: 'Michelle' },
  { value: 'eVXYtPVYB9wDoz9NVTIy', title: 'Carla' },
  { value: 'iScHbNW8K33gNo3lGgbo', title: 'Marianne' },
  { value: 'eQnBc1norhy4xHHbr9Ip', title: 'Cielo' },
  { value: 'x3mAOLD9WzlmrFCwA1S3', title: 'Evelin Perdomo' },
  { value: 'lWq4KDY8znfkV0DrK8Vb', title: 'Yasmin Alves' },
  { value: 'x8udhExu0uJxUn4Tf9Az', title: 'Slany' },
  { value: 'MZxV5lN3cv7hi1376O0m', title: 'Ana Dias' },
  { value: 'QJd9SLe6MVCdF6DR0EAu', title: 'Gabby' },
  { value: 'vibfi5nlk3hs8Mtvf9Oy', title: 'Ana - Brazilian' },
  { value: 'FIEA0c5UHH9JnvWaQrXS', title: 'Michele - Brazilian' },
  { value: 'nHNZWlqUWtEKPr3hhFQP', title: 'Daiane Candido' },
  { value: 'Eyspt3SYhZzXd1Jd3J8O', title: 'Bia - Brazilian' },
  { value: 'e70XR1sNoAGoLxPGL5f6', title: 'Márcio (alternativo)' },
  { value: '6pQlwCgfwffNdI3jjzM6', title: 'Fernando Borges' },
  { value: 'ylkAmqCrRDIZwbkOGyJe', title: 'Wlademir' },
  { value: 'UPTmB6OygMADpd4LOwE5', title: 'Vinicius Bergamo' },
  { value: 'WFSxKvz27RguNRD3Phoq', title: 'Wesley Bessa' },
  { value: 'UNlPbm2VdUhPl6lNL6D6', title: 'Diego' },
  { value: 'n2aB5UDlpf5USMJH7Qst', title: 'Gilson Lima' },
  { value: '6dHxv8ke5peKaO9xM46v', title: 'Gustavo Jannuzzi' },
  { value: 'hd5xzUNI8bF3Lvk3KkTO', title: 'Juliana Barbieri' },
  { value: 'ZxeM4498ujGNHYhQXtLS', title: 'Davi' },
  { value: 'JNI7HKGyqNaHqfihNoCi', title: 'Rener' },
  { value: 'gwiHKiILZ18I7Pb40yFN', title: 'FMDAmbrosio' },
  { value: 'hwnuNyWkl9DjdTFykrN6', title: 'Adriano - Narrator' },
  { value: 'ZAYPVq9zNssSHWCf6pko', title: 'Roberto Barbieri' },
  { value: '9pDzHy2OpOgeXM8SeL0t', title: 'Borges' },
];
